<?php

namespace AppBundle\Repository;

/**
 * orderitemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemRepository extends \Doctrine\ORM\EntityRepository
{
}
