<?php

namespace AppBundle\Repository;

/**
 * photoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class photoRepository extends \Doctrine\ORM\EntityRepository
{
}
